# Updated to fix CORS issues - Force new deployment
[build]
  base = "movie-frontend"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_API_URL = "https://alx-project-nexus-production-f78f.up.railway.app"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific redirects (optional)
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "https://alx-project-nexus-production-f78f.up.railway.app/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "preview"
  REACT_APP_API_URL = "https://alx-project-nexus-production-f78f.up.railway.app/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "development"
  REACT_APP_API_URL = "https://alx-project-nexus-production-f78f.up.railway.app/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"