[build]
  command = "npm run build"
  publish = "build"

# 1) PROXY API THROUGH NETLIFY (no CORS in the browser)
[[redirects]]
  from = "/api/*"
  to = "https://alx-project-nexus-production-f78f.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "alx-project-nexus-production-f78f.up.railway.app" }

# 2) React SPA fallback (keep AFTER the API redirect)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # IMPORTANT: point the app to the same-origin proxy in prod
  REACT_APP_API_URL = "/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# Security/Perf headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow same-origin + any HTTPS for APIs/images/etc (you can tighten later)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Per-context env still pointing to /api (NOT the Railway URL)
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "preview"
  REACT_APP_API_URL = "/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "development"
  REACT_APP_API_URL = "/api"
  CI = "false"
  GENERATE_SOURCEMAP = "false"