[build]
builder = "railpack"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput --settings=movie_backend.production_settings"
watchPatterns = ["./**"]

[project]
root = "."

[deploy]
startCommand = "python manage.py migrate --settings=movie_backend.production_settings && gunicorn movie_backend.wsgi:application --bind 0.0.0.0:$PORT --env DJANGO_SETTINGS_MODULE=movie_backend.production_settings"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
RAILWAY_STATIC_URL = "/static/"
DJANGO_SETTINGS_MODULE = "movie_backend.production_settings"
PYTHONPATH = "."
PORT = "8000"